import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const main = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");
const preload = await readFile(new URL("../electron/preload.cjs", import.meta.url), "utf8");
const terminal = await readFile(new URL("../src/index.html", import.meta.url), "utf8");
const call = await readFile(new URL("../src/call.html", import.meta.url), "utf8");
const callScript = await readFile(new URL("../src/call.js", import.meta.url), "utf8");
const appScript = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
const nativeCapture = await readFile(new URL("../electron/screen-access.c", import.meta.url), "utf8");
const afterSign = await readFile(new URL("../scripts/after-sign.cjs", import.meta.url), "utf8");
const takeoverMarkup = await readFile(new URL("../src/takeover.html", import.meta.url), "utf8");
const takeover = await readFile(new URL("../src/takeover.js", import.meta.url), "utf8");
const takeoverStyles = await readFile(new URL("../src/takeover.css", import.meta.url), "utf8");

test("presents the deep-space contact sequence before the incoming call", () => {
  assert.match(terminal, /深空文明主动联络终端/);
  assert.match(terminal, /向宇宙发送呼叫/);
  assert.match(terminal, /建立非人类协议握手/);
  assert.match(call, /未知星际联系人/);
  assert.match(call, /拒绝/);
  assert.doesNotMatch(call, /wechat-dot/);
  assert.match(callScript, /HANDOFF TO COURTESY ENGINE/);
  assert.match(callScript, /window\.spaceTerminal\.rejectCall\(\)/);
  assert.doesNotMatch(callScript, /setTimeout\(\(\) => window\.spaceTerminal\.rejectCall/);
});

test("desktop takeover is visual-only and always recoverable", () => {
  assert.match(main, /desktopCapturer\.getSources/);
  assert.match(main, /display\.scaleFactor/);
  assert.match(main, /3840/);
  assert.match(main, /toPNG/);
  assert.match(main, /input\.key === "Escape"/);
  assert.match(main, /roundedCorners: false/);
  assert.match(main, /const overscan = 8/);
  assert.match(takeoverMarkup, /ufo-flight/);
  assert.match(takeoverMarkup, /ufo-transparent-v2\.png/);
  assert.match(takeover, /createAbductionObjects/);
  assert.match(takeover, /startParticleVortex/);
  assert.match(takeoverStyles, /@keyframes ufo-fly-in/);
  assert.match(takeoverStyles, /@keyframes object-vacuum/);
  assert.match(takeover, /restoreDesktop/);
  assert.match(takeover, /releaseSnapshot/);
  assert.match(takeover, /abductionObjects\.replaceChildren/);
  assert.match(takeover, /URL\.createObjectURL/);
  assert.match(takeover, /URL\.revokeObjectURL/);
  assert.match(preload, /pendingTakeoverInit/);
  assert.match(preload, /queueMicrotask/);
  assert.match(main, /takeover-render-ready/);
  assert.match(main, /captureBelowTakeoverWindow/);
  assert.match(main, /getMediaSourceId/);
  assert.match(main, /takeover-background/);
  assert.match(preload, /onTakeoverBackground/);
  assert.match(nativeCapture, /CGWindowListCreateImage/);
  assert.match(nativeCapture, /kCGWindowListOptionOnScreenBelowWindow/);
  assert.match(nativeCapture, /captureBelowWindow/);
  assert.match(afterSign, /signAsync/);
  assert.match(afterSign, /findLocalSigningIdentity/);
  assert.match(afterSign, /Developer ID Application\|Apple Development/);
  assert.match(afterSign, /"--verify"/);
  assert.match(afterSign, /"--deep"/);
  assert.match(takeover, /takeoverRenderReady/);
  assert.match(takeover, /installDesktopBackground/);
  assert.match(takeover, /onTakeoverBackground/);
  assert.match(main, /fetchWindowIcons: true/);
  assert.match(main, /source\.appIcon/);
  assert.match(main, /captureOpenAppIcons/);
  assert.match(main, /snapshot, appIcons/);
  assert.match(main, /Menu\.setApplicationMenu\(Menu\.buildFromTemplate/);
  assert.match(main, /退出深空文明呼叫终端/);
  assert.match(takeover, /native-window-icon/);
  assert.match(takeover, /desktop-dock-crop/);
  assert.match(takeover, /desktop-snapshot/);
  assert.doesNotMatch(takeover, /--app-color|linear-gradient\(145deg,#6ee7ff/);
  assert.doesNotMatch(`${takeoverMarkup}\n${takeoverStyles}\n${takeover}`, /asset-card|object-file|FINAL_FINAL|9,284 ITEMS/);
  assert.doesNotMatch(`${takeoverMarkup}\n${takeoverStyles}\n${takeover}`, /desktop-tile|tile-abduct|createTiles/);
  assert.doesNotMatch(main, /unlink|renameSync|rmSync|writeFile|trashItem/);
});

test("the rejection escalates into a visible comedic final result", () => {
  assert.match(takeoverMarkup, /你的原始拒接理由/);
  assert.match(takeoverMarkup, /我现在不方便接听/);
  assert.match(takeoverMarkup, /大模型高情商翻译中/);
  assert.match(takeoverMarkup, /大模型高情商翻译结果/);
  assert.match(takeoverMarkup, /贵文明暂未达到本用户的通话标准/);
  assert.match(takeover, /已发送至来电文明/);
  assert.match(takeoverMarkup, /对方正在输入/);
  assert.match(takeoverMarkup, /对方没有继续反驳/);
  assert.match(takeoverMarkup, /远端草稿 · 尚未发送/);
  assert.match(takeover, /typeAlienDraft\("你们这个文明……"\)/);
  assert.match(takeover, /typingText\.textContent = "对方正在删除……"/);
  assert.match(takeover, /typeAlienDraft\("算了。"\)/);
  assert.match(takeover, /typingText\.textContent = "对方又删除了……"/);
  assert.match(takeover, /typingText\.textContent = "对方没有继续反驳"/);
  assert.match(takeoverMarkup, /对方已带走电脑里的所有资料/);
  assert.match(takeoverMarkup, /设备本体已为你保留/);
  assert.match(takeoverMarkup, /设备使用权恢复倒计时/);
  assert.match(takeoverMarkup, /9999年 364天 23:59:59/);
  assert.match(takeoverMarkup, /大模型贴心解读/);
  assert.match(takeoverMarkup, /对方祝福你能活一万岁/);
  assert.match(takeoverStyles, /\.is-final \.final-message/);
  assert.match(takeoverStyles, /\.is-data-gone \.result-data/);
  assert.match(takeoverStyles, /\.is-device-kept \.result-device/);
  assert.match(takeoverStyles, /\.is-locked \.unlock-panel/);
  assert.match(takeoverStyles, /\.is-comforted \.ai-comfort/);
  assert.match(takeover, /对方已抵达本地桌面/);
  assert.match(takeover, /INITIAL_UNLOCK_SECONDS/);
  assert.match(takeover, /startUnlockCountdown/);
  assert.doesNotMatch(`${takeoverMarkup}\n${takeover}`, /2 厘米|1 米|10 米|整个桌面|37%|68%|100%/);
});

test("screen capture permission is verified and refreshed after returning from settings", () => {
  assert.match(main, /verify-capture-access/);
  assert.match(main, /request-capture-access/);
  assert.match(main, /CGRequestScreenCaptureAccess|screen-access\.node/);
  assert.match(main, /capture-status-refresh/);
  assert.match(appScript, /requestCaptureAccess/);
  assert.match(appScript, /captureReady/);
  assert.match(appScript, /桌面捕获已就绪/);
  assert.match(appScript, /5200/);
  assert.match(appScript, /window\.addEventListener\("focus"/);
  assert.match(appScript, /visibilitychange/);
});
